version: '3'
services:
  scrape_anything:
    build:
      context: .
      dockerfile: Dockerfile
      target: prod
    ports:
     - 3000:3000
    environment:
      - OPENAI_API=${OPENAI_API}
    volumes:
      - ./outputs:/usr/src/app/outputs